const express = require('express');
const app = express();

let middleware = require('./middleware');

/*
 * This middleware function parses JSON in the body of POST requests
 */
app.use(express.json());

/*
 * This middleware function will respond to improperly formed JSON in
 * request parameters.
 */
app.use(middleware.jsonErrorInBody);

app.use('/auth', require('./routes/signin.js'));

app.use('/auth', require('./routes/register.js'));

app.use('/confirmation', require('./routes/confirmation.js'));

app.listen(process.env.PORT || 5000, () => {
  console.log('Server up and running on port: ' + (process.env.PORT || 5000));
});

/*
 * Serve the API documentation generated by apidoc as HTML.
 * https://apidocjs.com/
 */
app.use('/doc', express.static('apidoc'));
